//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Console_TelegramBot {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    internal sealed partial class Console_TelegramBot : global::System.Configuration.ApplicationSettingsBase {
        
        private static Console_TelegramBot defaultInstance = ((Console_TelegramBot)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Console_TelegramBot())));
        
        public static Console_TelegramBot Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5181007101:AAGZ_TEpFLE3SUuc2jfE_8x3qSliH89g8-Q")]
        public string BotKey {
            get {
                return ((string)(this["BotKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=TG_Test_Bot;Integrated Securit" +
            "y=True")]
        public string ConnString {
            get {
                return ((string)(this["ConnString"]));
            }
        }
    }
}
